// ─── Sanity Schema: Photo ─────────────────────────────────────────────────────
// This defines the shape of a "photo" document in your Sanity CMS.
// Import this into your sanity.config.ts:
//   import photo from './schemas/photo'
//   export default defineConfig({ schema: { types: [photo] } })

import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'photo',
  title: 'Photo',
  type: 'document',

  // Optional: customise the preview shown in the Sanity list view
  preview: {
    select: {
      title: 'title',
      subtitle: 'location',
      media: 'image',
    },
  },

  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      description: 'A short, descriptive title for this photo',
      validation: (Rule) => Rule.required().min(3).max(80),
    }),

    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      options: {
        hotspot: true, // lets you set a focal point for smart cropping
      },
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags', // renders as a tag input in the dashboard
      },
      description: 'Add keywords: species, technique, location, equipment, mood…',
    }),

    defineField({
      name: 'aiCaption',
      title: 'AI Caption',
      type: 'text',
      rows: 3,
      // readOnly hides the edit button in the studio — caption is set by the webhook
      readOnly: true,
      description: 'Auto-generated by Claude when you publish. Do not edit manually.',
    }),

    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      description: 'e.g. "Red Sea, Egypt" or "Monterey Bay, California"',
    }),

    defineField({
      name: 'camera',
      title: 'Camera & Lens',
      type: 'string',
      description: 'e.g. "Nikon Z8 + 28-80mm, Nauticam housing"',
    }),

    defineField({
      name: 'dateTaken',
      title: 'Date Taken',
      type: 'date',
    }),

    defineField({
      name: 'visible',
      title: 'Visible in gallery',
      type: 'boolean',
      description: 'Uncheck to hide this photo from the public gallery without deleting it.',
      initialValue: true,
    }),
  ],
})
