import {defineField, defineType} from 'sanity'

export const photoType = defineType({
  name: 'photo',
  title: 'Photo',
  type: 'document',

  preview: {
    select: {
      title: 'title',
      subtitle: 'location',
      media: 'image',
    },
  },

  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (rule) => rule.required().min(3).max(80),
    }),

    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      options: {hotspot: true},
      validation: (rule) => rule.required(),
    }),

    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
      description: 'Add keywords: species, technique, location, equipment…',
    }),

    defineField({
      name: 'aiCaption',
      title: 'AI Caption',
      type: 'text',
      rows: 3,
      readOnly: true,
      description: 'Auto-generated by Claude when you publish. Do not edit manually.',
    }),

    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      description: 'e.g. "Truk Lagoon, Micronesia"',
    }),

    defineField({
      name: 'camera',
      title: 'Camera & Lens',
      type: 'string',
      description: 'e.g. "Nikon Z8 + 28-80mm, Nauticam housing"',
    }),

    defineField({
      name: 'dateTaken',
      title: 'Date Taken',
      type: 'date',
    }),

    defineField({
      name: 'lens',
      title: 'Lens',
      type: 'string',
      description: 'e.g. "Sigma 15mm f/2.8 Fisheye"',
    }),

    defineField({
      name: 'focalLength',
      title: 'Focal Length',
      type: 'string',
      description: 'e.g. "15mm"',
    }),

    defineField({
      name: 'iso',
      title: 'ISO',
      type: 'string',
      description: 'e.g. "800"',
    }),

    defineField({
      name: 'shutterSpeed',
      title: 'Shutter Speed',
      type: 'string',
      description: 'e.g. "1/250"',
    }),

    defineField({
      name: 'aperture',
      title: 'Aperture',
      type: 'string',
      description: 'e.g. "f/2.8"',
    }),

    defineField({
      name: 'visible',
      title: 'Visible in gallery',
      type: 'boolean',
      description: 'Uncheck to hide this photo from the public gallery without deleting it.',
      initialValue: true,
    }),
  ],
})
